name: TradeShop
version: 1.6.0-BETA
main: org.shanerx.tradeshop.TradeShop

author: Lori00
authors: [KillerOfPie]
description: A new powerful trading plugin.

commands:
  tradeshop:
    description: Core command for TradeShop
    aliases: [ts]