name: TradeShop
version: 2.2.0
main: org.shanerx.tradeshop.TradeShop
api-version: 1.13
load: POSTWORLD

authors: [Lori00, KillerOfPie]
description: A new powerful economy trading plugin based on sign-chest shops.
website: https://www.spigotmc.org/resources/tradeshop.32762/

commands:
  tradeshop:
    description: Core command for TradeShop
    aliases: [ts]
