name: TradeShop
version: 2.2.2-BETA
main: org.shanerx.tradeshop.TradeShop
api-version: 1.13
load: POSTWORLD

authors: [Lori00, KillerOfPie]
description: A powerful trading plugin based on sign-chest shops.
website: https://tradeshop.github.io, https://www.spigotmc.org/resources/tradeshop.32762/

commands:
  tradeshop:
    description: Core command for TradeShop
    aliases: [ts]
