name: TradeShop
version: 1.7.0-BETA
main: org.shanerx.tradeshop.TradeShop

author: Lori00
authors: [KillerOfPie]
description: A new powerful trading plugin.
website: https://www.spigotmc.org/resources/tradeshop.32762/

commands:
  tradeshop:
    description: Core command for TradeShop
    aliases: [ts]