name: TradeShop
<<<<<<< HEAD
version: 2.0.0-DEV
=======
version: 1.8.1
>>>>>>> origin
main: org.shanerx.tradeshop.TradeShop

author: Lori00
authors: [KillerOfPie]
description: A new powerful trading plugin.
website: https://www.spigotmc.org/resources/tradeshop.32762/

commands:
  tradeshop:
    description: Core command for TradeShop
    aliases: [ts]