name: TradeShop
version: 1.3.0
author: Lori00
main: org.shanerx.tradeshop.TradeShop

description: A new powerful trading plugin.

commands:
  tradeshop:
    description: Core command for TradeShop
    aliases: [ts]