name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Package with Maven
      run: mvn deploy -Dregistry=https://maven.pkg.github.com/Tradeshop -Dtoken=${{ secrets.GITHUB_TOKEN }}
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name:  Tradeshop Build
        path: '/home/runner/work/TradeShop/TradeShop/target/*.jar'
